name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./GbrSchedulero
      run: dotnet restore
    - name: Build
      working-directory: ./GbrSchedulero
      run: dotnet build --no-restore 
    - name: Test
      working-directory: ./GbrSchedulero
      env: 
        DB_SECRET: ${{secrets.DATABASEPASSWORD}}
      run: dotnet test --no-build --verbosity normal "$DB_SECRET"
